# Combining outputs & treshold

This notebook provides code to combine various output .csv's with predictions, and provide a way to set a treshold for a quick evaluation of the models confidence.

In [1]:
import glob
import os
import pandas as pd

#for tensor
import fastai
from fastai.vision.all import *

In [2]:
%%time 

version = 'v03'
folder_name = 'preds/Preds_new_data/'+version
file_type = 'csv'
seperator =','

CPU times: user 12 µs, sys: 0 ns, total: 12 µs
Wall time: 21.5 µs

In [ ]:
dataframe = pd.concat([pd.read_csv(f, sep=seperator) for f in glob.glob(folder_name + "/*."+file_type)],ignore_index=True)

In [3]:
%%time

dataframe
#dataframe.head()

CPU times: user 5 µs, sys: 1e+03 ns, total: 6 µs
Wall time: 9.54 µs

,id,label,0,1,2,3,4,5,6,7,...,56,57,58,59,60,61,62,63,64,65
0,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/Background.tif,2,1.252000e-06,2.488689e-03,9.454492e-01,1.420000e-07,3.300000e-07,3.560000e-07,1.360080e-04,5.500000e-07,...,2.061800e-05,1.150000e-07,4.100000e-07,4.800000e-08,3.572000e-06,6.000000e-08,1.192000e-06,8.980000e-07,1.230000e-07,2.847000e-05
1,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000000.tif,35,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.000000e-09,0.000000e+00,0.000000e+00,1.000000e-09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000001.tif,26,0.000000e+00,9.300000e-08,3.140000e-07,0.000000e+00,8.000000e-09,1.000000e-09,2.900000e-08,3.000000e-09,...,2.000000e-09,0.000000e+00,5.800000e-08,2.000000e-09,2.300000e-08,0.000000e+00,1.450000e-07,8.000000e-09,0.000000e+00,2.810000e-07
3,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000002.tif,35,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,1.000000e-09,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e-09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000003.tif,32,9.500000e-08,3.233900e-05,2.220100e-05,2.000000e-08,1.300000e-08,1.331000e-06,1.265100e-05,1.090000e-07,...,4.810000e-07,5.540000e-07,5.200000e-08,2.800000e-08,8.280000e-07,3.900000e-08,4.590000e-06,1.862000e-06,1.090000e-07,6.990000e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85689620,../Project003a_Plankton_imager/data_tar/2023-06-07/untarred_1950/RawImages/pia6.2023-06-07.1950+N00001043.tif,34,1.179000e-06,1.326000e-04,1.443000e-05,2.100000e-08,9.000000e-08,1.017000e-06,1.103600e-05,9.720000e-07,...,5.158000e-06,4.900000e-08,1.590000e-07,2.090000e-07,7.280400e-05,2.670000e-07,1.112500e-05,9.300000e-08,4.100000e-08,7.650000e-07
85689621,../Project003a_Plankton_imager/data_tar/2023-06-07/untarred_1950/RawImages/pia6.2023-06-07.1950+N00001044.tif,50,1.260000e-07,1.100000e-08,5.300000e-08,1.000000e-09,0.000000e+00,2.000000e-09,2.700000e-08,3.050000e-06,...,4.800000e-08,6.100000e-08,0.000000e+00,1.300000e-08,4.000000e-09,2.260000e-07,2.200000e-08,1.430000e-07,1.000000e-09,2.700000e-08
85689622,../Project003a_Plankton_imager/data_tar/2023-06-07/untarred_1950/RawImages/pia6.2023-06-07.1950+N00001045.tif,52,2.700000e-07,1.762000e-06,2.230000e-07,0.000000e+00,0.000000e+00,9.200000e-08,4.280000e-07,1.586900e-05,...,1.770000e-07,1.100000e-08,1.100000e-08,5.069000e-06,1.117900e-05,1.300000e-08,3.000000e-09,2.500000e-08,7.100000e-08,1.110000e-07
85689623,../Project003a_Plankton_imager/data_tar/2023-06-07/untarred_1950/RawImages/pia6.2023-06-07.1950+N00001046.tif,49,8.000000e-09,2.041000e-06,1.000000e-09,0.000000e+00,1.000000e-09,2.000000e-09,1.000000e-09,1.002000e-06,...,7.000000e-09,0.000000e+00,7.900000e-08,0.000000e+00,1.000000e-08,3.650900e-05,1.044740e-04,8.000000e-08,1.100000e-08,5.000000e-09
85689624,../Project003a_Plankton_imager/data_tar/2023-06-07/untarred_1950/RawImages/pia6.2023-06-07.1950+N00001047.tif,61,7.850500e-05,1.578000e-06,1.320000e-07,3.000000e-09,3.000000e-09,1.100000e-08,3.500000e-08,2.600600e-05,...,6.605000e-06,2.790000e-07,2.850000e-07,9.550000e-07,5.470000e-07,9.302499e-01,9.900000e-07,8.340000e-07,1.160000e-07,2.800000e-08

In [4]:
%%time

# Change to tensor and extract highest value
dataframe_tensor = torch.tensor(dataframe.iloc[:,2:].to_numpy())
out, inds = torch.max(dataframe_tensor,dim=1)

CPU times: user 49.6 s, sys: 54.7 s, total: 1min 44s
Wall time: 25.8 s

In [5]:
%%time

# For dataframe collected from separate files (see above)

# Evaluate how many preds are above treshold

# Set threshold value
threshold = .98

# Create tensor with True/False for every value in y
b = out > threshold

# Calculate number of images above threshold
ImageNr = len(dataframe_tensor[b]) 
# Calculate percentage of images above threshold
ImagePerc = (len(dataframe_tensor[b])*100/len(dataframe_tensor))

print (ImageNr, 'images (i.e.,', float("{:.2f}".format(ImagePerc)), 
       '%) of predictions are above the threshold of', threshold)
print()

49674675 images (i.e., 57.97 %) of predictions are above the threshold of 0.98

CPU times: user 52.8 s, sys: 57.8 s, total: 1min 50s
Wall time: 12 s

In [6]:
%%time

# Add column number and highest value of preds to table
dataframe['out'] = out
dataframe['inds'] = inds

CPU times: user 243 ms, sys: 375 ms, total: 618 ms
Wall time: 625 ms

In [7]:
%%time

dataframe.head()

CPU times: user 183 µs, sys: 41 µs, total: 224 µs
Wall time: 214 µs

,id,label,0,1,2,3,4,5,6,7,...,58,59,60,61,62,63,64,65,out,inds
0,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/Background.tif,2,1.252000e-06,2.488689e-03,9.454492e-01,1.420000e-07,3.300000e-07,3.560000e-07,1.360080e-04,5.500000e-07,...,4.100000e-07,4.800000e-08,3.572000e-06,6.000000e-08,1.192000e-06,8.980000e-07,1.230000e-07,2.847000e-05,0.945449,2
1,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000000.tif,35,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,1.000000e-09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.999999,35
2,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000001.tif,26,0.000000e+00,9.300000e-08,3.140000e-07,0.000000e+00,8.000000e-09,1.000000e-09,2.900000e-08,3.000000e-09,...,5.800000e-08,2.000000e-09,2.300000e-08,0.000000e+00,1.450000e-07,8.000000e-09,0.000000e+00,2.810000e-07,0.995639,26
3,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000002.tif,35,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e-09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.999999,35
4,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000003.tif,32,9.500000e-08,3.233900e-05,2.220100e-05,2.000000e-08,1.300000e-08,1.331000e-06,1.265100e-05,1.090000e-07,...,5.200000e-08,2.800000e-08,8.280000e-07,3.900000e-08,4.590000e-06,1.862000e-06,1.090000e-07,6.990000e-07,0.501893,32

In [8]:
%%time

# Export table to .csv file for downstream applications
# Reduced decimal points by '%.3f'
dataframe.to_csv(version+'_All_data.csv', index=False, float_format='%.3f')

CPU times: user 2h 41min 8s, sys: 57 s, total: 2h 42min 5s
Wall time: 2h 42min 13s

### Some checks to see output

In [3]:
%%time

# Checked what takes longer: (i) read every csv seprately and conc (see above), 
# or (ii) read combined csv file

# Reading csv file is faster, and less prone to inconsistencies

dataframe2 = pd.read_csv(version+'_All_data.csv')

CPU times: user 8min 56s, sys: 1min 23s, total: 10min 19s
Wall time: 10min 19s

In [4]:
%%time

# Also, check if decimal points are okay:
dataframe2.head()

CPU times: user 267 µs, sys: 14 µs, total: 281 µs
Wall time: 270 µs

,id,label,0,1,2,3,4,5,6,7,...,58,59,60,61,62,63,64,65,out,inds
0,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/Background.tif,2,0.0,0.002,0.945,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.945,2
1,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000000.tif,35,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000,35
2,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000001.tif,26,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.996,26
3,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000002.tif,35,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000,35
4,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000003.tif,32,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.502,32

In [5]:
%%time

# Also, check number of rows is equal to concatenated version above:
dataframe2

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 8.11 µs

,id,label,0,1,2,3,4,5,6,7,...,58,59,60,61,62,63,64,65,out,inds
0,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/Background.tif,2,0.0,0.002,0.945,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.945,2
1,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000000.tif,35,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.000,35
2,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000001.tif,26,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.996,26
3,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000002.tif,35,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.000,35
4,../Project003a_Plankton_imager/data_tar/2023-06-09/untarred_0000/RawImages/pia6.2023-06-09.0000+N00000003.tif,32,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.502,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85689620,../Project003a_Plankton_imager/data_tar/2023-06-07/untarred_1950/RawImages/pia6.2023-06-07.1950+N00001043.tif,34,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.577,34
85689621,../Project003a_Plankton_imager/data_tar/2023-06-07/untarred_1950/RawImages/pia6.2023-06-07.1950+N00001044.tif,50,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.000,50
85689622,../Project003a_Plankton_imager/data_tar/2023-06-07/untarred_1950/RawImages/pia6.2023-06-07.1950+N00001045.tif,52,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.989,52
85689623,../Project003a_Plankton_imager/data_tar/2023-06-07/untarred_1950/RawImages/pia6.2023-06-07.1950+N00001046.tif,49,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,1.000,49
85689624,../Project003a_Plankton_imager/data_tar/2023-06-07/untarred_1950/RawImages/pia6.2023-06-07.1950+N00001047.tif,61,0.0,0.000,0.000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.93,0.0,0.0,0.0,0.0,0.930,61

In case csv is too large, try below (not tested)

In [ ]:
import pandas as pd

# Define the chunk size (e.g., 100,000 rows at a time)
chunk_size = 100000
chunks = []

for chunk in pd.read_csv(version+'_All_data.csv', chunksize=chunk_size):
    # Process each chunk and append to the list (if necessary)
    chunks.append(chunk)

# Combine all chunks into a single DataFrame
dataframe2 = pd.concat(chunks, ignore_index=True)